# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.harvesterhci_io_v1beta1_virtual_machine_image_spec import HarvesterhciIoV1beta1VirtualMachineImageSpec  # noqa: E501
from harvester.rest import ApiException


class TestHarvesterhciIoV1beta1VirtualMachineImageSpec(unittest.TestCase):
    """HarvesterhciIoV1beta1VirtualMachineImageSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHarvesterhciIoV1beta1VirtualMachineImageSpec(self):
        """Test HarvesterhciIoV1beta1VirtualMachineImageSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.harvesterhci_io_v1beta1_virtual_machine_image_spec.HarvesterhciIoV1beta1VirtualMachineImageSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
