# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.kubevirt_io_api_core_v1_host_disk import KubevirtIoApiCoreV1HostDisk  # noqa: E501
from harvester.rest import ApiException


class TestKubevirtIoApiCoreV1HostDisk(unittest.TestCase):
    """KubevirtIoApiCoreV1HostDisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubevirtIoApiCoreV1HostDisk(self):
        """Test KubevirtIoApiCoreV1HostDisk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.kubevirt_io_api_core_v1_host_disk.KubevirtIoApiCoreV1HostDisk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
