# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.network_harvesterhci_io_v1beta1_link_status import NetworkHarvesterhciIoV1beta1LinkStatus  # noqa: E501
from harvester.rest import ApiException


class TestNetworkHarvesterhciIoV1beta1LinkStatus(unittest.TestCase):
    """NetworkHarvesterhciIoV1beta1LinkStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkHarvesterhciIoV1beta1LinkStatus(self):
        """Test NetworkHarvesterhciIoV1beta1LinkStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.network_harvesterhci_io_v1beta1_link_status.NetworkHarvesterhciIoV1beta1LinkStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
