# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.k8s_cni_cncf_io_v1_network_attachment_definition_spec import K8sCniCncfIoV1NetworkAttachmentDefinitionSpec  # noqa: E501
from harvester.rest import ApiException


class TestK8sCniCncfIoV1NetworkAttachmentDefinitionSpec(unittest.TestCase):
    """K8sCniCncfIoV1NetworkAttachmentDefinitionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sCniCncfIoV1NetworkAttachmentDefinitionSpec(self):
        """Test K8sCniCncfIoV1NetworkAttachmentDefinitionSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.k8s_cni_cncf_io_v1_network_attachment_definition_spec.K8sCniCncfIoV1NetworkAttachmentDefinitionSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
