# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.kubevirt_io_api_core_v1_kernel_boot_container import KubevirtIoApiCoreV1KernelBootContainer  # noqa: E501
from harvester.rest import ApiException


class TestKubevirtIoApiCoreV1KernelBootContainer(unittest.TestCase):
    """KubevirtIoApiCoreV1KernelBootContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubevirtIoApiCoreV1KernelBootContainer(self):
        """Test KubevirtIoApiCoreV1KernelBootContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.kubevirt_io_api_core_v1_kernel_boot_container.KubevirtIoApiCoreV1KernelBootContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
