# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.kubevirt_io_api_core_v1_resource_requirements import KubevirtIoApiCoreV1ResourceRequirements  # noqa: E501
from harvester.rest import ApiException


class TestKubevirtIoApiCoreV1ResourceRequirements(unittest.TestCase):
    """KubevirtIoApiCoreV1ResourceRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubevirtIoApiCoreV1ResourceRequirements(self):
        """Test KubevirtIoApiCoreV1ResourceRequirements"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.kubevirt_io_api_core_v1_resource_requirements.KubevirtIoApiCoreV1ResourceRequirements()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
