# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.harvesterhci_io_v1beta1_key_pair import HarvesterhciIoV1beta1KeyPair  # noqa: E501
from harvester.rest import ApiException


class TestHarvesterhciIoV1beta1KeyPair(unittest.TestCase):
    """HarvesterhciIoV1beta1KeyPair unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHarvesterhciIoV1beta1KeyPair(self):
        """Test HarvesterhciIoV1beta1KeyPair"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.harvesterhci_io_v1beta1_key_pair.HarvesterhciIoV1beta1KeyPair()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
