# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.k8s_io_v1_pod_anti_affinity import K8sIoV1PodAntiAffinity  # noqa: E501
from harvester.rest import ApiException


class TestK8sIoV1PodAntiAffinity(unittest.TestCase):
    """K8sIoV1PodAntiAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sIoV1PodAntiAffinity(self):
        """Test K8sIoV1PodAntiAffinity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.k8s_io_v1_pod_anti_affinity.K8sIoV1PodAntiAffinity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
