# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.kubevirt_io_containerized_data_importer_api_pkg_apis_core_v1beta1_data_volume_source_registry import KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry  # noqa: E501
from harvester.rest import ApiException


class TestKubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry(unittest.TestCase):
    """KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry(self):
        """Test KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.kubevirt_io_containerized_data_importer_api_pkg_apis_core_v1beta1_data_volume_source_registry.KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRegistry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
