# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.api.networks_api import NetworksApi  # noqa: E501
from harvester.rest import ApiException


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self):
        self.api = harvester.api.networks_api.NetworksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_namespaced_cluster_network(self):
        """Test case for create_namespaced_cluster_network

        """
        pass

    def test_create_namespaced_network_attachment_definition(self):
        """Test case for create_namespaced_network_attachment_definition

        """
        pass

    def test_create_namespaced_node_network(self):
        """Test case for create_namespaced_node_network

        """
        pass

    def test_delete_namespaced_cluster_network(self):
        """Test case for delete_namespaced_cluster_network

        """
        pass

    def test_delete_namespaced_network_attachment_definition(self):
        """Test case for delete_namespaced_network_attachment_definition

        """
        pass

    def test_delete_namespaced_node_network(self):
        """Test case for delete_namespaced_node_network

        """
        pass

    def test_list_namespaced_cluster_network(self):
        """Test case for list_namespaced_cluster_network

        """
        pass

    def test_list_namespaced_network_attachment_definition(self):
        """Test case for list_namespaced_network_attachment_definition

        """
        pass

    def test_list_namespaced_node_network(self):
        """Test case for list_namespaced_node_network

        """
        pass

    def test_list_network_attachment_definition_for_all_namespaces(self):
        """Test case for list_network_attachment_definition_for_all_namespaces

        """
        pass

    def test_patch_namespaced_cluster_network(self):
        """Test case for patch_namespaced_cluster_network

        """
        pass

    def test_patch_namespaced_network_attachment_definition(self):
        """Test case for patch_namespaced_network_attachment_definition

        """
        pass

    def test_patch_namespaced_node_network(self):
        """Test case for patch_namespaced_node_network

        """
        pass

    def test_read_namespaced_cluster_network(self):
        """Test case for read_namespaced_cluster_network

        """
        pass

    def test_read_namespaced_network_attachment_definition(self):
        """Test case for read_namespaced_network_attachment_definition

        """
        pass

    def test_read_namespaced_node_network(self):
        """Test case for read_namespaced_node_network

        """
        pass

    def test_replace_namespaced_cluster_network(self):
        """Test case for replace_namespaced_cluster_network

        """
        pass

    def test_replace_namespaced_network_attachment_definition(self):
        """Test case for replace_namespaced_network_attachment_definition

        """
        pass

    def test_replace_namespaced_node_network(self):
        """Test case for replace_namespaced_node_network

        """
        pass


if __name__ == '__main__':
    unittest.main()
