# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import harvester
from harvester.models.k8s_io_v1_local_object_reference import K8sIoV1LocalObjectReference  # noqa: E501
from harvester.rest import ApiException


class TestK8sIoV1LocalObjectReference(unittest.TestCase):
    """K8sIoV1LocalObjectReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testK8sIoV1LocalObjectReference(self):
        """Test K8sIoV1LocalObjectReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = harvester.models.k8s_io_v1_local_object_reference.K8sIoV1LocalObjectReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
