/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1Firmware struct {
	// Settings to control the bootloader that is used.
	Bootloader *KubevirtIoApiCoreV1Bootloader `json:"bootloader,omitempty"`
	// Settings to set the kernel for booting.
	KernelBoot *KubevirtIoApiCoreV1KernelBoot `json:"kernelBoot,omitempty"`
	// The system-serial-number in SMBIOS
	Serial string `json:"serial,omitempty"`
	// UUID reported by the vmi bios. Defaults to a random generated uid.
	Uuid string `json:"uuid,omitempty"`
}
