/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type HarvesterhciIoV1beta1PersistentVolumeClaimSourceSpec struct {
	Metadata *K8sIoV1ObjectMeta `json:"metadata,omitempty"`
	Spec *K8sIoV1PersistentVolumeClaimSpec `json:"spec,omitempty"`
}
