/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1Interface struct {
	// BootOrder is an integer value > 0, used to determine ordering of boot devices. Lower values take precedence. Each interface or disk that has a boot order must have a unique value. Interfaces without a boot order are not tried.
	BootOrder int32 `json:"bootOrder,omitempty"`
	Bridge *KubevirtIoApiCoreV1InterfaceBridge `json:"bridge,omitempty"`
	// If specified the network interface will pass additional DHCP options to the VMI
	DhcpOptions *KubevirtIoApiCoreV1DhcpOptions `json:"dhcpOptions,omitempty"`
	// Interface MAC address. For example: de:ad:00:00:be:af or DE-AD-00-00-BE-AF.
	MacAddress string `json:"macAddress,omitempty"`
	Macvtap *KubevirtIoApiCoreV1InterfaceMacvtap `json:"macvtap,omitempty"`
	Masquerade *KubevirtIoApiCoreV1InterfaceMasquerade `json:"masquerade,omitempty"`
	// Interface model. One of: e1000, e1000e, ne2k_pci, pcnet, rtl8139, virtio. Defaults to virtio.
	Model string `json:"model,omitempty"`
	// Logical name of the interface as well as a reference to the associated networks. Must match the Name of a Network.
	Name string `json:"name"`
	// If specified, the virtual network interface will be placed on the guests pci address with the specified PCI address. For example: 0000:81:01.10
	PciAddress string `json:"pciAddress,omitempty"`
	// List of ports to be forwarded to the virtual machine.
	Ports []KubevirtIoApiCoreV1Port `json:"ports,omitempty"`
	Slirp *KubevirtIoApiCoreV1InterfaceSlirp `json:"slirp,omitempty"`
	Sriov *KubevirtIoApiCoreV1InterfaceSriov `json:"sriov,omitempty"`
	// If specified, the virtual network interface address and its tag will be provided to the guest via config drive
	Tag string `json:"tag,omitempty"`
}
