/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1SyNicTimer struct {
	Direct *KubevirtIoApiCoreV1FeatureState `json:"direct,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}
