/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeSourcePVC provides the parameters to create a Data Volume from an existing PVC
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourcePvc struct {
	// The name of the source PVC
	Name string `json:"name"`
	// The namespace of the source PVC
	Namespace string `json:"namespace"`
}
