/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// If set (default), BIOS will be used.
type KubevirtIoApiCoreV1Bios struct {
	// If set, the BIOS output will be transmitted over serial
	UseSerial bool `json:"useSerial,omitempty"`
}
