/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// ResourceFieldSelector represents container resources (cpu, memory) and their output format
type K8sIoV1ResourceFieldSelector struct {
	// Container name: required for volumes, optional for env vars
	ContainerName string `json:"containerName,omitempty"`
	// Specifies the output format of the exposed resources, defaults to \"1\"
	Divisor *K8sIoApimachineryPkgApiResourceQuantity `json:"divisor,omitempty"`
	// Required: resource to select
	Resource string `json:"resource"`
}
