/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type HarvesterhciIoV1beta1VirtualMachineTemplateStatus struct {
	DefaultVersion int32 `json:"defaultVersion,omitempty"`
	LatestVersion int32 `json:"latestVersion,omitempty"`
}
