/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// RemoveVolumeOptions is provided when dynamically hot unplugging volume and disk
type KubevirtIoApiCoreV1RemoveVolumeOptions struct {
	// When present, indicates that modifications should not be persisted. An invalid or unrecognized dryRun directive will result in an error response and no further processing of the request. Valid values are: - All: all dry run stages will be processed
	DryRun []string `json:"dryRun,omitempty"`
	// Name represents the name that maps to both the disk and volume that should be removed
	Name string `json:"name"`
}
