/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents the stock pod network interface.
type KubevirtIoApiCoreV1PodNetwork struct {
	// IPv6 CIDR for the vm network. Defaults to fd10:0:2::/120 if not specified.
	VmIPv6NetworkCIDR string `json:"vmIPv6NetworkCIDR,omitempty"`
	// CIDR for vm network. Default 10.0.2.0/24 if not specified.
	VmNetworkCIDR string `json:"vmNetworkCIDR,omitempty"`
}
