/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Chassis specifies the chassis info passed to the domain.
type KubevirtIoApiCoreV1Chassis struct {
	Asset string `json:"asset,omitempty"`
	Manufacturer string `json:"manufacturer,omitempty"`
	Serial string `json:"serial,omitempty"`
	Sku string `json:"sku,omitempty"`
	Version string `json:"version,omitempty"`
}
