/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents if a feature is enabled or disabled.
type KubevirtIoApiCoreV1FeatureState struct {
	// Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.
	Enabled bool `json:"enabled,omitempty"`
}
