/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents the multus cni network.
type KubevirtIoApiCoreV1MultusNetwork struct {
	// Select the default network and add it to the multus-cni.io/default-network annotation.
	Default_ bool `json:"default,omitempty"`
	// References to a NetworkAttachmentDefinition CRD object. Format: <networkName>, <namespace>/<networkName>. If namespace is not specified, VMI namespace is assumed.
	NetworkName string `json:"networkName"`
}
