/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1VirtualMachineInstanceMigrationState struct {
	// Indicates that the migration has been requested to abort
	AbortRequested bool `json:"abortRequested,omitempty"`
	// Indicates the final status of the live migration abortion
	AbortStatus string `json:"abortStatus,omitempty"`
	// Indicates the migration completed
	Completed bool `json:"completed,omitempty"`
	// The time the migration action ended
	EndTimestamp *K8sIoV1Time `json:"endTimestamp,omitempty"`
	// Indicates that the migration failed
	Failed bool `json:"failed,omitempty"`
	// Migration configurations to apply
	MigrationConfiguration *KubevirtIoApiCoreV1MigrationConfiguration `json:"migrationConfiguration,omitempty"`
	// Name of the migration policy. If string is empty, no policy is matched
	MigrationPolicyName string `json:"migrationPolicyName,omitempty"`
	// The VirtualMachineInstanceMigration object associated with this migration
	MigrationUid string `json:"migrationUid,omitempty"`
	// Lets us know if the vmi is currently running pre or post copy migration
	Mode string `json:"mode,omitempty"`
	// The source node that the VMI originated on
	SourceNode string `json:"sourceNode,omitempty"`
	// The time the migration action began
	StartTimestamp *K8sIoV1Time `json:"startTimestamp,omitempty"`
	// The UID of the target attachment pod for hotplug volumes
	TargetAttachmentPodUID string `json:"targetAttachmentPodUID,omitempty"`
	// If the VMI requires dedicated CPUs, this field will hold the dedicated CPU set on the target node
	TargetCPUSet []int32 `json:"targetCPUSet,omitempty"`
	// The list of ports opened for live migration on the destination node
	TargetDirectMigrationNodePorts map[string]int32 `json:"targetDirectMigrationNodePorts,omitempty"`
	// The target node that the VMI is moving to
	TargetNode string `json:"targetNode,omitempty"`
	// The address of the target node to use for the migration
	TargetNodeAddress string `json:"targetNodeAddress,omitempty"`
	// The Target Node has seen the Domain Start Event
	TargetNodeDomainDetected bool `json:"targetNodeDomainDetected,omitempty"`
	// If the VMI requires dedicated CPUs, this field will hold the numa topology on the target node
	TargetNodeTopology string `json:"targetNodeTopology,omitempty"`
	// The target pod that the VMI is moving to
	TargetPod string `json:"targetPod,omitempty"`
}
