/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents a Sysprep volume source.
type KubevirtIoApiCoreV1SysprepSource struct {
	// ConfigMap references a ConfigMap that contains Sysprep answer file named autounattend.xml that should be attached as disk of CDROM type.
	ConfigMap *K8sIoV1LocalObjectReference `json:"configMap,omitempty"`
	// Secret references a k8s Secret that contains Sysprep answer file named autounattend.xml that should be attached as disk of CDROM type.
	Secret *K8sIoV1LocalObjectReference `json:"secret,omitempty"`
}
