/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1Gpu struct {
	DeviceName string `json:"deviceName"`
	// Name of the GPU device as exposed by a device plugin
	Name string `json:"name"`
	// If specified, the virtual network interface address and its tag will be provided to the guest via config drive
	Tag string `json:"tag,omitempty"`
	VirtualGPUOptions *KubevirtIoApiCoreV1VgpuOptions `json:"virtualGPUOptions,omitempty"`
}
