/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents the clock and timers of a vmi.
type KubevirtIoApiCoreV1Clock struct {
	// Timer specifies whih timers are attached to the vmi.
	Timer *KubevirtIoApiCoreV1Timer `json:"timer,omitempty"`
	// Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. 'America/New_York').
	Timezone string `json:"timezone,omitempty"`
	// UTC sets the guest clock to UTC on each boot. If an offset is specified, guest changes to the clock will be kept during reboots and are not reset.
	Utc *KubevirtIoApiCoreV1ClockOffsetUtc `json:"utc,omitempty"`
}
