/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1DataVolumeSource struct {
	// Hotpluggable indicates whether the volume can be hotplugged and hotunplugged.
	Hotpluggable bool `json:"hotpluggable,omitempty"`
	// Name represents the name of the DataVolume in the same namespace
	Name string `json:"name"`
}
