/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Error is the last error encountered during the snapshot/restore
type HarvesterhciIoV1beta1Error struct {
	Message string `json:"message,omitempty"`
	Time *K8sIoV1Time `json:"time,omitempty"`
}
