/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1FeatureSpinlocks struct {
	// Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.
	Enabled bool `json:"enabled,omitempty"`
	// Retries indicates the number of retries. Must be a value greater or equal 4096. Defaults to 4096.
	Spinlocks int64 `json:"spinlocks,omitempty"`
}
