/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// VirtualMachineBackupStatus is the status for a VirtualMachineBackup resource
type HarvesterhciIoV1beta1VirtualMachineBackupStatus struct {
	BackupTarget *HarvesterhciIoV1beta1BackupTarget `json:"backupTarget,omitempty"`
	Conditions []HarvesterhciIoV1beta1Condition `json:"conditions,omitempty"`
	CreationTime *K8sIoV1Time `json:"creationTime,omitempty"`
	Error_ *HarvesterhciIoV1beta1Error `json:"error,omitempty"`
	ReadyToUse bool `json:"readyToUse,omitempty"`
	SecretBackups []HarvesterhciIoV1beta1SecretBackup `json:"secretBackups,omitempty"`
	// SourceSpec contains the vm spec source of the backup target
	Source *HarvesterhciIoV1beta1VirtualMachineSourceSpec `json:"source,omitempty"`
	SourceUID string `json:"sourceUID,omitempty"`
	VolumeBackups []HarvesterhciIoV1beta1VolumeBackup `json:"volumeBackups,omitempty"`
}
