/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
type K8sIoV1WeightedPodAffinityTerm struct {
	// Required. A pod affinity term, associated with the corresponding weight.
	PodAffinityTerm *K8sIoV1PodAffinityTerm `json:"podAffinityTerm"`
	// weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
	Weight int32 `json:"weight"`
}
