/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DHCPExtraOptions defines Extra DHCP options for a VM.
type KubevirtIoApiCoreV1DhcpPrivateOptions struct {
	// Option is an Integer value from 224-254 Required.
	Option int32 `json:"option"`
	// Value is a String value for the Option provided Required.
	Value string `json:"value"`
}
