/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeBlankImage provides the parameters to create a new raw blank image for the PVC
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeBlankImage struct {
}
