/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// InterfaceBridge connects to a given network via a linux bridge.
type KubevirtIoApiCoreV1InterfaceBridge struct {
}
