/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DownwardAPIVolumeSource represents a volume containing downward API info.
type KubevirtIoApiCoreV1DownwardApiVolumeSource struct {
	// Fields is a list of downward API volume file
	Fields []K8sIoV1DownwardApiVolumeFile `json:"fields,omitempty"`
	// The volume label of the resulting disk inside the VMI. Different bootstrapping mechanisms require different values. Typical values are \"cidata\" (cloud-init), \"config-2\" (cloud-init) or \"OEMDRV\" (kickstart).
	VolumeLabel string `json:"volumeLabel,omitempty"`
}
