/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type NetworkHarvesterhciIoV1beta1NodeNetworkSpec struct {
	Description string `json:"description,omitempty"`
	Nic string `json:"nic,omitempty"`
	NodeName string `json:"nodeName"`
	Type_ string `json:"type,omitempty"`
}
