/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1ResourceRequirements struct {
	// Limits describes the maximum amount of compute resources allowed. Valid resource keys are \"memory\" and \"cpu\".
	Limits map[string]K8sIoApimachineryPkgApiResourceQuantity `json:"limits,omitempty"`
	// Don't ask the scheduler to take the guest-management overhead into account. Instead put the overhead only into the container's memory limit. This can lead to crashes if all memory is in use on a node. Defaults to false.
	OvercommitGuestOverhead bool `json:"overcommitGuestOverhead,omitempty"`
	// Requests is a description of the initial vmi resources. Valid resource keys are \"memory\" and \"cpu\".
	Requests map[string]K8sIoApimachineryPkgApiResourceQuantity `json:"requests,omitempty"`
}
