/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents a cloud-init config drive user data source. More info: https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html
type KubevirtIoApiCoreV1CloudInitConfigDriveSource struct {
	// NetworkData contains config drive inline cloud-init networkdata.
	NetworkData string `json:"networkData,omitempty"`
	// NetworkDataBase64 contains config drive cloud-init networkdata as a base64 encoded string.
	NetworkDataBase64 string `json:"networkDataBase64,omitempty"`
	// NetworkDataSecretRef references a k8s secret that contains config drive networkdata.
	NetworkDataSecretRef *K8sIoV1LocalObjectReference `json:"networkDataSecretRef,omitempty"`
	// UserDataSecretRef references a k8s secret that contains config drive userdata.
	SecretRef *K8sIoV1LocalObjectReference `json:"secretRef,omitempty"`
	// UserData contains config drive inline cloud-init userdata.
	UserData string `json:"userData,omitempty"`
	// UserDataBase64 contains config drive cloud-init userdata as a base64 encoded string.
	UserDataBase64 string `json:"userDataBase64,omitempty"`
}
