/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1LaunchSecurity struct {
	// AMD Secure Encrypted Virtualization (SEV).
	Sev *KubevirtIoApiCoreV1Sev `json:"sev,omitempty"`
}
