/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1Machine struct {
	// QEMU machine type is the actual chipset of the VirtualMachineInstance.
	Type_ string `json:"type,omitempty"`
}
