/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// VirtualMachineStartFailure tracks VMIs which failed to transition successfully to running using the VM status
type KubevirtIoApiCoreV1VirtualMachineStartFailure struct {
	ConsecutiveFailCount int32 `json:"consecutiveFailCount,omitempty"`
	LastFailedVMIUID string `json:"lastFailedVMIUID,omitempty"`
	RetryAfterTimestamp *K8sIoV1Time `json:"retryAfterTimestamp,omitempty"`
}
