/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1Input struct {
	// Bus indicates the bus of input device to emulate. Supported values: virtio, usb.
	Bus string `json:"bus,omitempty"`
	// Name is the device name
	Name string `json:"name"`
	// Type indicated the type of input device. Supported values: tablet.
	Type_ string `json:"type"`
}
