/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Named watchdog device.
type KubevirtIoApiCoreV1Watchdog struct {
	// i6300esb watchdog device.
	I6300esb *KubevirtIoApiCoreV1I6300EsbWatchdog `json:"i6300esb,omitempty"`
	// Name of the watchdog.
	Name string `json:"name"`
}
