/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Represents the user's configuration to emulate sound cards in the VMI.
type KubevirtIoApiCoreV1SoundDevice struct {
	// We only support ich9 or ac97. If SoundDevice is not set: No sound card is emulated. If SoundDevice is set but Model is not: ich9
	Model string `json:"model,omitempty"`
	// User's defined name for this sound device
	Name string `json:"name"`
}
