/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type KubevirtIoApiCoreV1VirtualMachineInstanceCondition struct {
	LastProbeTime *K8sIoV1Time `json:"lastProbeTime,omitempty"`
	LastTransitionTime *K8sIoV1Time `json:"lastTransitionTime,omitempty"`
	Message string `json:"message,omitempty"`
	Reason string `json:"reason,omitempty"`
	Status string `json:"status"`
	Type_ string `json:"type"`
}
