/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeSourceRef defines an indirect reference to the source of data for the DataVolume
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceRef struct {
	// The kind of the source reference, currently only \"DataSource\" is supported
	Kind string `json:"kind"`
	// The name of the source reference
	Name string `json:"name"`
	// The namespace of the source reference, defaults to the DataVolume namespace
	Namespace string `json:"namespace,omitempty"`
}
