/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

type HarvesterhciIoV1beta1UpgradeStatus struct {
	Conditions []HarvesterhciIoV1beta1Condition `json:"conditions,omitempty"`
	ImageID string `json:"imageID,omitempty"`
	NodeStatuses map[string]HarvesterhciIoV1beta1NodeUpgradeStatus `json:"nodeStatuses,omitempty"`
	PreviousVersion string `json:"previousVersion,omitempty"`
	RepoInfo string `json:"repoInfo,omitempty"`
	SingleNode string `json:"singleNode,omitempty"`
}
