/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeSourceImageIO provides the parameters to create a Data Volume from an imageio source
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceImageIo struct {
	// CertConfigMap provides a reference to the CA cert
	CertConfigMap string `json:"certConfigMap,omitempty"`
	// DiskID provides id of a disk to be imported
	DiskId string `json:"diskId"`
	// SecretRef provides the secret reference needed to access the ovirt-engine
	SecretRef string `json:"secretRef,omitempty"`
	// URL is the URL of the ovirt-engine
	Url string `json:"url"`
}
