/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// Memory allows specifying the VirtualMachineInstance memory features.
type KubevirtIoApiCoreV1Memory struct {
	// Guest allows to specifying the amount of memory which is visible inside the Guest OS. The Guest must lie between Requests and Limits from the resources section. Defaults to the requested memory in the resources section if not specified.
	Guest *K8sIoApimachineryPkgApiResourceQuantity `json:"guest,omitempty"`
	// Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.
	Hugepages *KubevirtIoApiCoreV1Hugepages `json:"hugepages,omitempty"`
}
