/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// i6300esb watchdog device.
type KubevirtIoApiCoreV1I6300EsbWatchdog struct {
	// The action to take. Valid values are poweroff, reset, shutdown. Defaults to reset.
	Action string `json:"action,omitempty"`
}
