/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// VirtualMachineRestoreStatus is the spec for a VirtualMachineRestore resource
type HarvesterhciIoV1beta1VirtualMachineRestoreStatus struct {
	Complete bool `json:"complete,omitempty"`
	Conditions []HarvesterhciIoV1beta1Condition `json:"conditions,omitempty"`
	DeletedVolumes []string `json:"deletedVolumes,omitempty"`
	RestoreTime *K8sIoV1Time `json:"restoreTime,omitempty"`
	Restores []HarvesterhciIoV1beta1VolumeRestore `json:"restores,omitempty"`
	TargetUID string `json:"targetUID,omitempty"`
}
