/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeCheckpoint defines a stage in a warm migration.
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeCheckpoint struct {
	// Current is the identifier of the snapshot created for this checkpoint.
	Current string `json:"current"`
	// Previous is the identifier of the snapshot from the previous checkpoint.
	Previous string `json:"previous"`
}
