/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// SSHPublicKeyAccessCredentialPropagationMethod represents the method used to inject a ssh public key into the vm guest. Only one of its members may be specified.
type KubevirtIoApiCoreV1SshPublicKeyAccessCredentialPropagationMethod struct {
	// ConfigDrivePropagation means that the ssh public keys are injected into the VM using metadata using the configDrive cloud-init provider
	ConfigDrive *KubevirtIoApiCoreV1ConfigDriveSshPublicKeyAccessCredentialPropagation `json:"configDrive,omitempty"`
	// QemuGuestAgentAccessCredentailPropagation means ssh public keys are dynamically injected into the vm at runtime via the qemu guest agent. This feature requires the qemu guest agent to be running within the guest.
	QemuGuestAgent *KubevirtIoApiCoreV1QemuGuestAgentSshPublicKeyAccessCredentialPropagation `json:"qemuGuestAgent,omitempty"`
}
