/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// PodDNSConfigOption defines DNS resolver options of a pod.
type K8sIoV1PodDnsConfigOption struct {
	// Required.
	Name string `json:"name,omitempty"`
	Value string `json:"value,omitempty"`
}
