/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// DataVolumeSourceS3 provides the parameters to create a Data Volume from an S3 source
type KubevirtIoContainerizedDataImporterApiPkgApisCoreV1beta1DataVolumeSourceS3 struct {
	// CertConfigMap is a configmap reference, containing a Certificate Authority(CA) public key, and a base64 encoded pem certificate
	CertConfigMap string `json:"certConfigMap,omitempty"`
	// SecretRef provides the secret reference needed to access the S3 source
	SecretRef string `json:"secretRef,omitempty"`
	// URL is the url of the S3 source
	Url string `json:"url"`
}
