/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// SecretBackup contains the secret data need to restore a secret referenced by the VM
type HarvesterhciIoV1beta1SecretBackup struct {
	Data map[string]string `json:"data,omitempty"`
	Name string `json:"name,omitempty"`
}
