/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
type K8sIoV1NodeSelectorTerm struct {
	// A list of node selector requirements by node's labels.
	MatchExpressions []K8sIoV1NodeSelectorRequirement `json:"matchExpressions,omitempty"`
	// A list of node selector requirements by node's fields.
	MatchFields []K8sIoV1NodeSelectorRequirement `json:"matchFields,omitempty"`
}
