/*
 * Harvester APIs
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1beta1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package harvester

// UTC sets the guest clock to UTC on each boot.
type KubevirtIoApiCoreV1ClockOffsetUtc struct {
	// OffsetSeconds specifies an offset in seconds, relative to UTC. If set, guest changes to the clock will be kept during reboots and not reset.
	OffsetSeconds int32 `json:"offsetSeconds,omitempty"`
}
