# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class HarvesterhciIoV1beta1KeyPairStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[HarvesterhciIoV1beta1Condition]',
        'finger_print': 'str'
    }

    attribute_map = {
        'conditions': 'conditions',
        'finger_print': 'fingerPrint'
    }

    def __init__(self, conditions=None, finger_print=None, _configuration=None):  # noqa: E501
        """HarvesterhciIoV1beta1KeyPairStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._conditions = None
        self._finger_print = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions
        if finger_print is not None:
            self.finger_print = finger_print

    @property
    def conditions(self):
        """Gets the conditions of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501


        :return: The conditions of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501
        :rtype: list[HarvesterhciIoV1beta1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this HarvesterhciIoV1beta1KeyPairStatus.


        :param conditions: The conditions of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501
        :type: list[HarvesterhciIoV1beta1Condition]
        """

        self._conditions = conditions

    @property
    def finger_print(self):
        """Gets the finger_print of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501


        :return: The finger_print of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501
        :rtype: str
        """
        return self._finger_print

    @finger_print.setter
    def finger_print(self, finger_print):
        """Sets the finger_print of this HarvesterhciIoV1beta1KeyPairStatus.


        :param finger_print: The finger_print of this HarvesterhciIoV1beta1KeyPairStatus.  # noqa: E501
        :type: str
        """

        self._finger_print = finger_print

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HarvesterhciIoV1beta1KeyPairStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HarvesterhciIoV1beta1KeyPairStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HarvesterhciIoV1beta1KeyPairStatus):
            return True

        return self.to_dict() != other.to_dict()
