# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class HarvesterhciIoV1beta1VirtualMachineTemplateSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'default_version_id': 'str',
        'description': 'str'
    }

    attribute_map = {
        'default_version_id': 'defaultVersionId',
        'description': 'description'
    }

    def __init__(self, default_version_id='', description=None, _configuration=None):  # noqa: E501
        """HarvesterhciIoV1beta1VirtualMachineTemplateSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._default_version_id = None
        self._description = None
        self.discriminator = None

        if default_version_id is not None:
            self.default_version_id = default_version_id
        if description is not None:
            self.description = description

    @property
    def default_version_id(self):
        """Gets the default_version_id of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501


        :return: The default_version_id of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501
        :rtype: str
        """
        return self._default_version_id

    @default_version_id.setter
    def default_version_id(self, default_version_id):
        """Sets the default_version_id of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.


        :param default_version_id: The default_version_id of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501
        :type: str
        """

        self._default_version_id = default_version_id

    @property
    def description(self):
        """Gets the description of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501


        :return: The description of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.


        :param description: The description of this HarvesterhciIoV1beta1VirtualMachineTemplateSpec.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HarvesterhciIoV1beta1VirtualMachineTemplateSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HarvesterhciIoV1beta1VirtualMachineTemplateSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HarvesterhciIoV1beta1VirtualMachineTemplateSpec):
            return True

        return self.to_dict() != other.to_dict()
