# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class HarvesterhciIoV1beta1SupportBundleStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[HarvesterhciIoV1beta1Condition]',
        'filename': 'str',
        'filesize': 'int',
        'progress': 'int',
        'state': 'str'
    }

    attribute_map = {
        'conditions': 'conditions',
        'filename': 'filename',
        'filesize': 'filesize',
        'progress': 'progress',
        'state': 'state'
    }

    def __init__(self, conditions=None, filename=None, filesize=None, progress=None, state=None, _configuration=None):  # noqa: E501
        """HarvesterhciIoV1beta1SupportBundleStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._conditions = None
        self._filename = None
        self._filesize = None
        self._progress = None
        self._state = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions
        if filename is not None:
            self.filename = filename
        if filesize is not None:
            self.filesize = filesize
        if progress is not None:
            self.progress = progress
        if state is not None:
            self.state = state

    @property
    def conditions(self):
        """Gets the conditions of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501


        :return: The conditions of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :rtype: list[HarvesterhciIoV1beta1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this HarvesterhciIoV1beta1SupportBundleStatus.


        :param conditions: The conditions of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :type: list[HarvesterhciIoV1beta1Condition]
        """

        self._conditions = conditions

    @property
    def filename(self):
        """Gets the filename of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501


        :return: The filename of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this HarvesterhciIoV1beta1SupportBundleStatus.


        :param filename: The filename of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :type: str
        """

        self._filename = filename

    @property
    def filesize(self):
        """Gets the filesize of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501


        :return: The filesize of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :rtype: int
        """
        return self._filesize

    @filesize.setter
    def filesize(self, filesize):
        """Sets the filesize of this HarvesterhciIoV1beta1SupportBundleStatus.


        :param filesize: The filesize of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :type: int
        """

        self._filesize = filesize

    @property
    def progress(self):
        """Gets the progress of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501


        :return: The progress of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this HarvesterhciIoV1beta1SupportBundleStatus.


        :param progress: The progress of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :type: int
        """

        self._progress = progress

    @property
    def state(self):
        """Gets the state of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501


        :return: The state of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this HarvesterhciIoV1beta1SupportBundleStatus.


        :param state: The state of this HarvesterhciIoV1beta1SupportBundleStatus.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HarvesterhciIoV1beta1SupportBundleStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HarvesterhciIoV1beta1SupportBundleStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HarvesterhciIoV1beta1SupportBundleStatus):
            return True

        return self.to_dict() != other.to_dict()
