# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class HarvesterhciIoV1beta1SupportBundleSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'issue_url': 'str'
    }

    attribute_map = {
        'description': 'description',
        'issue_url': 'issueURL'
    }

    def __init__(self, description='', issue_url='', _configuration=None):  # noqa: E501
        """HarvesterhciIoV1beta1SupportBundleSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._issue_url = None
        self.discriminator = None

        self.description = description
        if issue_url is not None:
            self.issue_url = issue_url

    @property
    def description(self):
        """Gets the description of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501


        :return: The description of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this HarvesterhciIoV1beta1SupportBundleSpec.


        :param description: The description of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def issue_url(self):
        """Gets the issue_url of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501


        :return: The issue_url of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501
        :rtype: str
        """
        return self._issue_url

    @issue_url.setter
    def issue_url(self, issue_url):
        """Sets the issue_url of this HarvesterhciIoV1beta1SupportBundleSpec.


        :param issue_url: The issue_url of this HarvesterhciIoV1beta1SupportBundleSpec.  # noqa: E501
        :type: str
        """

        self._issue_url = issue_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HarvesterhciIoV1beta1SupportBundleSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HarvesterhciIoV1beta1SupportBundleSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HarvesterhciIoV1beta1SupportBundleSpec):
            return True

        return self.to_dict() != other.to_dict()
