# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1SyNICTimer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'direct': 'KubevirtIoApiCoreV1FeatureState',
        'enabled': 'bool'
    }

    attribute_map = {
        'direct': 'direct',
        'enabled': 'enabled'
    }

    def __init__(self, direct=None, enabled=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1SyNICTimer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._direct = None
        self._enabled = None
        self.discriminator = None

        if direct is not None:
            self.direct = direct
        if enabled is not None:
            self.enabled = enabled

    @property
    def direct(self):
        """Gets the direct of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501


        :return: The direct of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1FeatureState
        """
        return self._direct

    @direct.setter
    def direct(self, direct):
        """Sets the direct of this KubevirtIoApiCoreV1SyNICTimer.


        :param direct: The direct of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501
        :type: KubevirtIoApiCoreV1FeatureState
        """

        self._direct = direct

    @property
    def enabled(self):
        """Gets the enabled of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501


        :return: The enabled of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this KubevirtIoApiCoreV1SyNICTimer.


        :param enabled: The enabled of this KubevirtIoApiCoreV1SyNICTimer.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1SyNICTimer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1SyNICTimer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1SyNICTimer):
            return True

        return self.to_dict() != other.to_dict()
