# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1EFI(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'secure_boot': 'bool'
    }

    attribute_map = {
        'secure_boot': 'secureBoot'
    }

    def __init__(self, secure_boot=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1EFI - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._secure_boot = None
        self.discriminator = None

        if secure_boot is not None:
            self.secure_boot = secure_boot

    @property
    def secure_boot(self):
        """Gets the secure_boot of this KubevirtIoApiCoreV1EFI.  # noqa: E501

        If set, SecureBoot will be enabled and the OVMF roms will be swapped for SecureBoot-enabled ones. Requires SMM to be enabled. Defaults to true  # noqa: E501

        :return: The secure_boot of this KubevirtIoApiCoreV1EFI.  # noqa: E501
        :rtype: bool
        """
        return self._secure_boot

    @secure_boot.setter
    def secure_boot(self, secure_boot):
        """Sets the secure_boot of this KubevirtIoApiCoreV1EFI.

        If set, SecureBoot will be enabled and the OVMF roms will be swapped for SecureBoot-enabled ones. Requires SMM to be enabled. Defaults to true  # noqa: E501

        :param secure_boot: The secure_boot of this KubevirtIoApiCoreV1EFI.  # noqa: E501
        :type: bool
        """

        self._secure_boot = secure_boot

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1EFI, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1EFI):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1EFI):
            return True

        return self.to_dict() != other.to_dict()
