# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1NUMA(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guest_mapping_passthrough': 'KubevirtIoApiCoreV1NUMAGuestMappingPassthrough'
    }

    attribute_map = {
        'guest_mapping_passthrough': 'guestMappingPassthrough'
    }

    def __init__(self, guest_mapping_passthrough=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1NUMA - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._guest_mapping_passthrough = None
        self.discriminator = None

        if guest_mapping_passthrough is not None:
            self.guest_mapping_passthrough = guest_mapping_passthrough

    @property
    def guest_mapping_passthrough(self):
        """Gets the guest_mapping_passthrough of this KubevirtIoApiCoreV1NUMA.  # noqa: E501

        GuestMappingPassthrough will create an efficient guest topology based on host CPUs exclusively assigned to a pod. The created topology ensures that memory and CPUs on the virtual numa nodes never cross boundaries of host numa nodes.  # noqa: E501

        :return: The guest_mapping_passthrough of this KubevirtIoApiCoreV1NUMA.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1NUMAGuestMappingPassthrough
        """
        return self._guest_mapping_passthrough

    @guest_mapping_passthrough.setter
    def guest_mapping_passthrough(self, guest_mapping_passthrough):
        """Sets the guest_mapping_passthrough of this KubevirtIoApiCoreV1NUMA.

        GuestMappingPassthrough will create an efficient guest topology based on host CPUs exclusively assigned to a pod. The created topology ensures that memory and CPUs on the virtual numa nodes never cross boundaries of host numa nodes.  # noqa: E501

        :param guest_mapping_passthrough: The guest_mapping_passthrough of this KubevirtIoApiCoreV1NUMA.  # noqa: E501
        :type: KubevirtIoApiCoreV1NUMAGuestMappingPassthrough
        """

        self._guest_mapping_passthrough = guest_mapping_passthrough

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1NUMA, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1NUMA):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1NUMA):
            return True

        return self.to_dict() != other.to_dict()
