# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1Devices(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'autoattach_graphics_device': 'bool',
        'autoattach_mem_balloon': 'bool',
        'autoattach_pod_interface': 'bool',
        'autoattach_serial_console': 'bool',
        'block_multi_queue': 'bool',
        'client_passthrough': 'KubevirtIoApiCoreV1ClientPassthroughDevices',
        'disable_hotplug': 'bool',
        'disks': 'list[KubevirtIoApiCoreV1Disk]',
        'filesystems': 'list[KubevirtIoApiCoreV1Filesystem]',
        'gpus': 'list[KubevirtIoApiCoreV1GPU]',
        'host_devices': 'list[KubevirtIoApiCoreV1HostDevice]',
        'inputs': 'list[KubevirtIoApiCoreV1Input]',
        'interfaces': 'list[KubevirtIoApiCoreV1Interface]',
        'network_interface_multiqueue': 'bool',
        'rng': 'KubevirtIoApiCoreV1Rng',
        'sound': 'KubevirtIoApiCoreV1SoundDevice',
        'tpm': 'KubevirtIoApiCoreV1TPMDevice',
        'use_virtio_transitional': 'bool',
        'watchdog': 'KubevirtIoApiCoreV1Watchdog'
    }

    attribute_map = {
        'autoattach_graphics_device': 'autoattachGraphicsDevice',
        'autoattach_mem_balloon': 'autoattachMemBalloon',
        'autoattach_pod_interface': 'autoattachPodInterface',
        'autoattach_serial_console': 'autoattachSerialConsole',
        'block_multi_queue': 'blockMultiQueue',
        'client_passthrough': 'clientPassthrough',
        'disable_hotplug': 'disableHotplug',
        'disks': 'disks',
        'filesystems': 'filesystems',
        'gpus': 'gpus',
        'host_devices': 'hostDevices',
        'inputs': 'inputs',
        'interfaces': 'interfaces',
        'network_interface_multiqueue': 'networkInterfaceMultiqueue',
        'rng': 'rng',
        'sound': 'sound',
        'tpm': 'tpm',
        'use_virtio_transitional': 'useVirtioTransitional',
        'watchdog': 'watchdog'
    }

    def __init__(self, autoattach_graphics_device=None, autoattach_mem_balloon=None, autoattach_pod_interface=None, autoattach_serial_console=None, block_multi_queue=None, client_passthrough=None, disable_hotplug=None, disks=None, filesystems=None, gpus=None, host_devices=None, inputs=None, interfaces=None, network_interface_multiqueue=None, rng=None, sound=None, tpm=None, use_virtio_transitional=None, watchdog=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1Devices - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._autoattach_graphics_device = None
        self._autoattach_mem_balloon = None
        self._autoattach_pod_interface = None
        self._autoattach_serial_console = None
        self._block_multi_queue = None
        self._client_passthrough = None
        self._disable_hotplug = None
        self._disks = None
        self._filesystems = None
        self._gpus = None
        self._host_devices = None
        self._inputs = None
        self._interfaces = None
        self._network_interface_multiqueue = None
        self._rng = None
        self._sound = None
        self._tpm = None
        self._use_virtio_transitional = None
        self._watchdog = None
        self.discriminator = None

        if autoattach_graphics_device is not None:
            self.autoattach_graphics_device = autoattach_graphics_device
        if autoattach_mem_balloon is not None:
            self.autoattach_mem_balloon = autoattach_mem_balloon
        if autoattach_pod_interface is not None:
            self.autoattach_pod_interface = autoattach_pod_interface
        if autoattach_serial_console is not None:
            self.autoattach_serial_console = autoattach_serial_console
        if block_multi_queue is not None:
            self.block_multi_queue = block_multi_queue
        if client_passthrough is not None:
            self.client_passthrough = client_passthrough
        if disable_hotplug is not None:
            self.disable_hotplug = disable_hotplug
        if disks is not None:
            self.disks = disks
        if filesystems is not None:
            self.filesystems = filesystems
        if gpus is not None:
            self.gpus = gpus
        if host_devices is not None:
            self.host_devices = host_devices
        if inputs is not None:
            self.inputs = inputs
        if interfaces is not None:
            self.interfaces = interfaces
        if network_interface_multiqueue is not None:
            self.network_interface_multiqueue = network_interface_multiqueue
        if rng is not None:
            self.rng = rng
        if sound is not None:
            self.sound = sound
        if tpm is not None:
            self.tpm = tpm
        if use_virtio_transitional is not None:
            self.use_virtio_transitional = use_virtio_transitional
        if watchdog is not None:
            self.watchdog = watchdog

    @property
    def autoattach_graphics_device(self):
        """Gets the autoattach_graphics_device of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach the default graphics device or not. VNC will not be available if set to false. Defaults to true.  # noqa: E501

        :return: The autoattach_graphics_device of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._autoattach_graphics_device

    @autoattach_graphics_device.setter
    def autoattach_graphics_device(self, autoattach_graphics_device):
        """Sets the autoattach_graphics_device of this KubevirtIoApiCoreV1Devices.

        Whether to attach the default graphics device or not. VNC will not be available if set to false. Defaults to true.  # noqa: E501

        :param autoattach_graphics_device: The autoattach_graphics_device of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._autoattach_graphics_device = autoattach_graphics_device

    @property
    def autoattach_mem_balloon(self):
        """Gets the autoattach_mem_balloon of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach the Memory balloon device with default period. Period can be adjusted in virt-config. Defaults to true.  # noqa: E501

        :return: The autoattach_mem_balloon of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._autoattach_mem_balloon

    @autoattach_mem_balloon.setter
    def autoattach_mem_balloon(self, autoattach_mem_balloon):
        """Sets the autoattach_mem_balloon of this KubevirtIoApiCoreV1Devices.

        Whether to attach the Memory balloon device with default period. Period can be adjusted in virt-config. Defaults to true.  # noqa: E501

        :param autoattach_mem_balloon: The autoattach_mem_balloon of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._autoattach_mem_balloon = autoattach_mem_balloon

    @property
    def autoattach_pod_interface(self):
        """Gets the autoattach_pod_interface of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach a pod network interface. Defaults to true.  # noqa: E501

        :return: The autoattach_pod_interface of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._autoattach_pod_interface

    @autoattach_pod_interface.setter
    def autoattach_pod_interface(self, autoattach_pod_interface):
        """Sets the autoattach_pod_interface of this KubevirtIoApiCoreV1Devices.

        Whether to attach a pod network interface. Defaults to true.  # noqa: E501

        :param autoattach_pod_interface: The autoattach_pod_interface of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._autoattach_pod_interface = autoattach_pod_interface

    @property
    def autoattach_serial_console(self):
        """Gets the autoattach_serial_console of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach the default serial console or not. Serial console access will not be available if set to false. Defaults to true.  # noqa: E501

        :return: The autoattach_serial_console of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._autoattach_serial_console

    @autoattach_serial_console.setter
    def autoattach_serial_console(self, autoattach_serial_console):
        """Sets the autoattach_serial_console of this KubevirtIoApiCoreV1Devices.

        Whether to attach the default serial console or not. Serial console access will not be available if set to false. Defaults to true.  # noqa: E501

        :param autoattach_serial_console: The autoattach_serial_console of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._autoattach_serial_console = autoattach_serial_console

    @property
    def block_multi_queue(self):
        """Gets the block_multi_queue of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether or not to enable virtio multi-queue for block devices. Defaults to false.  # noqa: E501

        :return: The block_multi_queue of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._block_multi_queue

    @block_multi_queue.setter
    def block_multi_queue(self, block_multi_queue):
        """Sets the block_multi_queue of this KubevirtIoApiCoreV1Devices.

        Whether or not to enable virtio multi-queue for block devices. Defaults to false.  # noqa: E501

        :param block_multi_queue: The block_multi_queue of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._block_multi_queue = block_multi_queue

    @property
    def client_passthrough(self):
        """Gets the client_passthrough of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        To configure and access client devices such as redirecting USB  # noqa: E501

        :return: The client_passthrough of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1ClientPassthroughDevices
        """
        return self._client_passthrough

    @client_passthrough.setter
    def client_passthrough(self, client_passthrough):
        """Sets the client_passthrough of this KubevirtIoApiCoreV1Devices.

        To configure and access client devices such as redirecting USB  # noqa: E501

        :param client_passthrough: The client_passthrough of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: KubevirtIoApiCoreV1ClientPassthroughDevices
        """

        self._client_passthrough = client_passthrough

    @property
    def disable_hotplug(self):
        """Gets the disable_hotplug of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        DisableHotplug disabled the ability to hotplug disks.  # noqa: E501

        :return: The disable_hotplug of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._disable_hotplug

    @disable_hotplug.setter
    def disable_hotplug(self, disable_hotplug):
        """Sets the disable_hotplug of this KubevirtIoApiCoreV1Devices.

        DisableHotplug disabled the ability to hotplug disks.  # noqa: E501

        :param disable_hotplug: The disable_hotplug of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._disable_hotplug = disable_hotplug

    @property
    def disks(self):
        """Gets the disks of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Disks describes disks, cdroms and luns which are connected to the vmi.  # noqa: E501

        :return: The disks of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1Disk]
        """
        return self._disks

    @disks.setter
    def disks(self, disks):
        """Sets the disks of this KubevirtIoApiCoreV1Devices.

        Disks describes disks, cdroms and luns which are connected to the vmi.  # noqa: E501

        :param disks: The disks of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1Disk]
        """

        self._disks = disks

    @property
    def filesystems(self):
        """Gets the filesystems of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Filesystems describes filesystem which is connected to the vmi.  # noqa: E501

        :return: The filesystems of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1Filesystem]
        """
        return self._filesystems

    @filesystems.setter
    def filesystems(self, filesystems):
        """Sets the filesystems of this KubevirtIoApiCoreV1Devices.

        Filesystems describes filesystem which is connected to the vmi.  # noqa: E501

        :param filesystems: The filesystems of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1Filesystem]
        """

        self._filesystems = filesystems

    @property
    def gpus(self):
        """Gets the gpus of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach a GPU device to the vmi.  # noqa: E501

        :return: The gpus of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1GPU]
        """
        return self._gpus

    @gpus.setter
    def gpus(self, gpus):
        """Sets the gpus of this KubevirtIoApiCoreV1Devices.

        Whether to attach a GPU device to the vmi.  # noqa: E501

        :param gpus: The gpus of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1GPU]
        """

        self._gpus = gpus

    @property
    def host_devices(self):
        """Gets the host_devices of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to attach a host device to the vmi.  # noqa: E501

        :return: The host_devices of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1HostDevice]
        """
        return self._host_devices

    @host_devices.setter
    def host_devices(self, host_devices):
        """Sets the host_devices of this KubevirtIoApiCoreV1Devices.

        Whether to attach a host device to the vmi.  # noqa: E501

        :param host_devices: The host_devices of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1HostDevice]
        """

        self._host_devices = host_devices

    @property
    def inputs(self):
        """Gets the inputs of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Inputs describe input devices  # noqa: E501

        :return: The inputs of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1Input]
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this KubevirtIoApiCoreV1Devices.

        Inputs describe input devices  # noqa: E501

        :param inputs: The inputs of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1Input]
        """

        self._inputs = inputs

    @property
    def interfaces(self):
        """Gets the interfaces of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Interfaces describe network interfaces which are added to the vmi.  # noqa: E501

        :return: The interfaces of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: list[KubevirtIoApiCoreV1Interface]
        """
        return self._interfaces

    @interfaces.setter
    def interfaces(self, interfaces):
        """Sets the interfaces of this KubevirtIoApiCoreV1Devices.

        Interfaces describe network interfaces which are added to the vmi.  # noqa: E501

        :param interfaces: The interfaces of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: list[KubevirtIoApiCoreV1Interface]
        """

        self._interfaces = interfaces

    @property
    def network_interface_multiqueue(self):
        """Gets the network_interface_multiqueue of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        If specified, virtual network interfaces configured with a virtio bus will also enable the vhost multiqueue feature for network devices. The number of queues created depends on additional factors of the VirtualMachineInstance, like the number of guest CPUs.  # noqa: E501

        :return: The network_interface_multiqueue of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._network_interface_multiqueue

    @network_interface_multiqueue.setter
    def network_interface_multiqueue(self, network_interface_multiqueue):
        """Sets the network_interface_multiqueue of this KubevirtIoApiCoreV1Devices.

        If specified, virtual network interfaces configured with a virtio bus will also enable the vhost multiqueue feature for network devices. The number of queues created depends on additional factors of the VirtualMachineInstance, like the number of guest CPUs.  # noqa: E501

        :param network_interface_multiqueue: The network_interface_multiqueue of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._network_interface_multiqueue = network_interface_multiqueue

    @property
    def rng(self):
        """Gets the rng of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to have random number generator from host  # noqa: E501

        :return: The rng of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1Rng
        """
        return self._rng

    @rng.setter
    def rng(self, rng):
        """Sets the rng of this KubevirtIoApiCoreV1Devices.

        Whether to have random number generator from host  # noqa: E501

        :param rng: The rng of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: KubevirtIoApiCoreV1Rng
        """

        self._rng = rng

    @property
    def sound(self):
        """Gets the sound of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to emulate a sound device.  # noqa: E501

        :return: The sound of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1SoundDevice
        """
        return self._sound

    @sound.setter
    def sound(self, sound):
        """Sets the sound of this KubevirtIoApiCoreV1Devices.

        Whether to emulate a sound device.  # noqa: E501

        :param sound: The sound of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: KubevirtIoApiCoreV1SoundDevice
        """

        self._sound = sound

    @property
    def tpm(self):
        """Gets the tpm of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Whether to emulate a TPM device.  # noqa: E501

        :return: The tpm of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1TPMDevice
        """
        return self._tpm

    @tpm.setter
    def tpm(self, tpm):
        """Sets the tpm of this KubevirtIoApiCoreV1Devices.

        Whether to emulate a TPM device.  # noqa: E501

        :param tpm: The tpm of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: KubevirtIoApiCoreV1TPMDevice
        """

        self._tpm = tpm

    @property
    def use_virtio_transitional(self):
        """Gets the use_virtio_transitional of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Fall back to legacy virtio 0.9 support if virtio bus is selected on devices. This is helpful for old machines like CentOS6 or RHEL6 which do not understand virtio_non_transitional (virtio 1.0).  # noqa: E501

        :return: The use_virtio_transitional of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: bool
        """
        return self._use_virtio_transitional

    @use_virtio_transitional.setter
    def use_virtio_transitional(self, use_virtio_transitional):
        """Sets the use_virtio_transitional of this KubevirtIoApiCoreV1Devices.

        Fall back to legacy virtio 0.9 support if virtio bus is selected on devices. This is helpful for old machines like CentOS6 or RHEL6 which do not understand virtio_non_transitional (virtio 1.0).  # noqa: E501

        :param use_virtio_transitional: The use_virtio_transitional of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: bool
        """

        self._use_virtio_transitional = use_virtio_transitional

    @property
    def watchdog(self):
        """Gets the watchdog of this KubevirtIoApiCoreV1Devices.  # noqa: E501

        Watchdog describes a watchdog device which can be added to the vmi.  # noqa: E501

        :return: The watchdog of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1Watchdog
        """
        return self._watchdog

    @watchdog.setter
    def watchdog(self, watchdog):
        """Sets the watchdog of this KubevirtIoApiCoreV1Devices.

        Watchdog describes a watchdog device which can be added to the vmi.  # noqa: E501

        :param watchdog: The watchdog of this KubevirtIoApiCoreV1Devices.  # noqa: E501
        :type: KubevirtIoApiCoreV1Watchdog
        """

        self._watchdog = watchdog

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1Devices, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1Devices):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1Devices):
            return True

        return self.to_dict() != other.to_dict()
