# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1LaunchSecurity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sev': 'KubevirtIoApiCoreV1SEV'
    }

    attribute_map = {
        'sev': 'sev'
    }

    def __init__(self, sev=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1LaunchSecurity - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._sev = None
        self.discriminator = None

        if sev is not None:
            self.sev = sev

    @property
    def sev(self):
        """Gets the sev of this KubevirtIoApiCoreV1LaunchSecurity.  # noqa: E501

        AMD Secure Encrypted Virtualization (SEV).  # noqa: E501

        :return: The sev of this KubevirtIoApiCoreV1LaunchSecurity.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1SEV
        """
        return self._sev

    @sev.setter
    def sev(self, sev):
        """Sets the sev of this KubevirtIoApiCoreV1LaunchSecurity.

        AMD Secure Encrypted Virtualization (SEV).  # noqa: E501

        :param sev: The sev of this KubevirtIoApiCoreV1LaunchSecurity.  # noqa: E501
        :type: KubevirtIoApiCoreV1SEV
        """

        self._sev = sev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1LaunchSecurity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1LaunchSecurity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1LaunchSecurity):
            return True

        return self.to_dict() != other.to_dict()
