# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1BIOS(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'use_serial': 'bool'
    }

    attribute_map = {
        'use_serial': 'useSerial'
    }

    def __init__(self, use_serial=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1BIOS - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._use_serial = None
        self.discriminator = None

        if use_serial is not None:
            self.use_serial = use_serial

    @property
    def use_serial(self):
        """Gets the use_serial of this KubevirtIoApiCoreV1BIOS.  # noqa: E501

        If set, the BIOS output will be transmitted over serial  # noqa: E501

        :return: The use_serial of this KubevirtIoApiCoreV1BIOS.  # noqa: E501
        :rtype: bool
        """
        return self._use_serial

    @use_serial.setter
    def use_serial(self, use_serial):
        """Sets the use_serial of this KubevirtIoApiCoreV1BIOS.

        If set, the BIOS output will be transmitted over serial  # noqa: E501

        :param use_serial: The use_serial of this KubevirtIoApiCoreV1BIOS.  # noqa: E501
        :type: bool
        """

        self._use_serial = use_serial

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1BIOS, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1BIOS):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1BIOS):
            return True

        return self.to_dict() != other.to_dict()
