# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metadata': 'K8sIoV1ObjectMeta',
        'spec': 'KubevirtIoApiCoreV1VirtualMachineInstanceSpec'
    }

    attribute_map = {
        'metadata': 'metadata',
        'spec': 'spec'
    }

    def __init__(self, metadata=None, spec=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._metadata = None
        self._spec = None
        self.discriminator = None

        if metadata is not None:
            self.metadata = metadata
        if spec is not None:
            self.spec = spec

    @property
    def metadata(self):
        """Gets the metadata of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501


        :return: The metadata of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501
        :rtype: K8sIoV1ObjectMeta
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.


        :param metadata: The metadata of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501
        :type: K8sIoV1ObjectMeta
        """

        self._metadata = metadata

    @property
    def spec(self):
        """Gets the spec of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501

        VirtualMachineInstance Spec contains the VirtualMachineInstance specification.  # noqa: E501

        :return: The spec of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1VirtualMachineInstanceSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.

        VirtualMachineInstance Spec contains the VirtualMachineInstance specification.  # noqa: E501

        :param spec: The spec of this KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec.  # noqa: E501
        :type: KubevirtIoApiCoreV1VirtualMachineInstanceSpec
        """

        self._spec = spec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VirtualMachineInstanceTemplateSpec):
            return True

        return self.to_dict() != other.to_dict()
