# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1BlockSize(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'custom': 'KubevirtIoApiCoreV1CustomBlockSize',
        'match_volume': 'KubevirtIoApiCoreV1FeatureState'
    }

    attribute_map = {
        'custom': 'custom',
        'match_volume': 'matchVolume'
    }

    def __init__(self, custom=None, match_volume=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1BlockSize - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._custom = None
        self._match_volume = None
        self.discriminator = None

        if custom is not None:
            self.custom = custom
        if match_volume is not None:
            self.match_volume = match_volume

    @property
    def custom(self):
        """Gets the custom of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501


        :return: The custom of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1CustomBlockSize
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this KubevirtIoApiCoreV1BlockSize.


        :param custom: The custom of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501
        :type: KubevirtIoApiCoreV1CustomBlockSize
        """

        self._custom = custom

    @property
    def match_volume(self):
        """Gets the match_volume of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501


        :return: The match_volume of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1FeatureState
        """
        return self._match_volume

    @match_volume.setter
    def match_volume(self, match_volume):
        """Sets the match_volume of this KubevirtIoApiCoreV1BlockSize.


        :param match_volume: The match_volume of this KubevirtIoApiCoreV1BlockSize.  # noqa: E501
        :type: KubevirtIoApiCoreV1FeatureState
        """

        self._match_volume = match_volume

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1BlockSize, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1BlockSize):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1BlockSize):
            return True

        return self.to_dict() != other.to_dict()
