# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1CustomBlockSize(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'logical': 'int',
        'physical': 'int'
    }

    attribute_map = {
        'logical': 'logical',
        'physical': 'physical'
    }

    def __init__(self, logical=0, physical=0, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1CustomBlockSize - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._logical = None
        self._physical = None
        self.discriminator = None

        self.logical = logical
        self.physical = physical

    @property
    def logical(self):
        """Gets the logical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501


        :return: The logical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501
        :rtype: int
        """
        return self._logical

    @logical.setter
    def logical(self, logical):
        """Sets the logical of this KubevirtIoApiCoreV1CustomBlockSize.


        :param logical: The logical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and logical is None:
            raise ValueError("Invalid value for `logical`, must not be `None`")  # noqa: E501

        self._logical = logical

    @property
    def physical(self):
        """Gets the physical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501


        :return: The physical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501
        :rtype: int
        """
        return self._physical

    @physical.setter
    def physical(self, physical):
        """Sets the physical of this KubevirtIoApiCoreV1CustomBlockSize.


        :param physical: The physical of this KubevirtIoApiCoreV1CustomBlockSize.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and physical is None:
            raise ValueError("Invalid value for `physical`, must not be `None`")  # noqa: E501

        self._physical = physical

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1CustomBlockSize, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1CustomBlockSize):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1CustomBlockSize):
            return True

        return self.to_dict() != other.to_dict()
