# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1VGPUDisplayOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enabled': 'bool',
        'ram_fb': 'KubevirtIoApiCoreV1FeatureState'
    }

    attribute_map = {
        'enabled': 'enabled',
        'ram_fb': 'ramFB'
    }

    def __init__(self, enabled=None, ram_fb=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1VGPUDisplayOptions - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._enabled = None
        self._ram_fb = None
        self.discriminator = None

        if enabled is not None:
            self.enabled = enabled
        if ram_fb is not None:
            self.ram_fb = ram_fb

    @property
    def enabled(self):
        """Gets the enabled of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501

        Enabled determines if a display addapter backed by a vGPU should be enabled or disabled on the guest. Defaults to true.  # noqa: E501

        :return: The enabled of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this KubevirtIoApiCoreV1VGPUDisplayOptions.

        Enabled determines if a display addapter backed by a vGPU should be enabled or disabled on the guest. Defaults to true.  # noqa: E501

        :param enabled: The enabled of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def ram_fb(self):
        """Gets the ram_fb of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501

        Enables a boot framebuffer, until the guest OS loads a real GPU driver Defaults to true.  # noqa: E501

        :return: The ram_fb of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501
        :rtype: KubevirtIoApiCoreV1FeatureState
        """
        return self._ram_fb

    @ram_fb.setter
    def ram_fb(self, ram_fb):
        """Sets the ram_fb of this KubevirtIoApiCoreV1VGPUDisplayOptions.

        Enables a boot framebuffer, until the guest OS loads a real GPU driver Defaults to true.  # noqa: E501

        :param ram_fb: The ram_fb of this KubevirtIoApiCoreV1VGPUDisplayOptions.  # noqa: E501
        :type: KubevirtIoApiCoreV1FeatureState
        """

        self._ram_fb = ram_fb

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1VGPUDisplayOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VGPUDisplayOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VGPUDisplayOptions):
            return True

        return self.to_dict() != other.to_dict()
