# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vmi_name': 'str'
    }

    attribute_map = {
        'vmi_name': 'vmiName'
    }

    def __init__(self, vmi_name=None, _configuration=None):  # noqa: E501
        """KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._vmi_name = None
        self.discriminator = None

        if vmi_name is not None:
            self.vmi_name = vmi_name

    @property
    def vmi_name(self):
        """Gets the vmi_name of this KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec.  # noqa: E501

        The name of the VMI to perform the migration on. VMI must exist in the migration objects namespace  # noqa: E501

        :return: The vmi_name of this KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec.  # noqa: E501
        :rtype: str
        """
        return self._vmi_name

    @vmi_name.setter
    def vmi_name(self, vmi_name):
        """Sets the vmi_name of this KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec.

        The name of the VMI to perform the migration on. VMI must exist in the migration objects namespace  # noqa: E501

        :param vmi_name: The vmi_name of this KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec.  # noqa: E501
        :type: str
        """

        self._vmi_name = vmi_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, KubevirtIoApiCoreV1VirtualMachineInstanceMigrationSpec):
            return True

        return self.to_dict() != other.to_dict()
