# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class NetworkHarvesterhciIoV1beta1NodeNetworkStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'conditions': 'list[NetworkHarvesterhciIoV1beta1Condition]',
        'network_i_ds': 'list[int]',
        'network_link_status': 'dict(str, NetworkHarvesterhciIoV1beta1LinkStatus)',
        'nics': 'list[NetworkHarvesterhciIoV1beta1NIC]'
    }

    attribute_map = {
        'conditions': 'conditions',
        'network_i_ds': 'networkIDs',
        'network_link_status': 'networkLinkStatus',
        'nics': 'nics'
    }

    def __init__(self, conditions=None, network_i_ds=None, network_link_status=None, nics=None, _configuration=None):  # noqa: E501
        """NetworkHarvesterhciIoV1beta1NodeNetworkStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._conditions = None
        self._network_i_ds = None
        self._network_link_status = None
        self._nics = None
        self.discriminator = None

        if conditions is not None:
            self.conditions = conditions
        if network_i_ds is not None:
            self.network_i_ds = network_i_ds
        if network_link_status is not None:
            self.network_link_status = network_link_status
        if nics is not None:
            self.nics = nics

    @property
    def conditions(self):
        """Gets the conditions of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501


        :return: The conditions of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :rtype: list[NetworkHarvesterhciIoV1beta1Condition]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.


        :param conditions: The conditions of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :type: list[NetworkHarvesterhciIoV1beta1Condition]
        """

        self._conditions = conditions

    @property
    def network_i_ds(self):
        """Gets the network_i_ds of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501


        :return: The network_i_ds of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :rtype: list[int]
        """
        return self._network_i_ds

    @network_i_ds.setter
    def network_i_ds(self, network_i_ds):
        """Sets the network_i_ds of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.


        :param network_i_ds: The network_i_ds of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :type: list[int]
        """

        self._network_i_ds = network_i_ds

    @property
    def network_link_status(self):
        """Gets the network_link_status of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501


        :return: The network_link_status of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :rtype: dict(str, NetworkHarvesterhciIoV1beta1LinkStatus)
        """
        return self._network_link_status

    @network_link_status.setter
    def network_link_status(self, network_link_status):
        """Sets the network_link_status of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.


        :param network_link_status: The network_link_status of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :type: dict(str, NetworkHarvesterhciIoV1beta1LinkStatus)
        """

        self._network_link_status = network_link_status

    @property
    def nics(self):
        """Gets the nics of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501


        :return: The nics of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :rtype: list[NetworkHarvesterhciIoV1beta1NIC]
        """
        return self._nics

    @nics.setter
    def nics(self, nics):
        """Sets the nics of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.


        :param nics: The nics of this NetworkHarvesterhciIoV1beta1NodeNetworkStatus.  # noqa: E501
        :type: list[NetworkHarvesterhciIoV1beta1NIC]
        """

        self._nics = nics

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkHarvesterhciIoV1beta1NodeNetworkStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkHarvesterhciIoV1beta1NodeNetworkStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkHarvesterhciIoV1beta1NodeNetworkStatus):
            return True

        return self.to_dict() != other.to_dict()
