# coding: utf-8

"""
    Harvester APIs

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from harvester.configuration import Configuration


class NetworkHarvesterhciIoV1beta1NodeNetworkSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'nic': 'str',
        'node_name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'description': 'description',
        'nic': 'nic',
        'node_name': 'nodeName',
        'type': 'type'
    }

    def __init__(self, description=None, nic=None, node_name='', type=None, _configuration=None):  # noqa: E501
        """NetworkHarvesterhciIoV1beta1NodeNetworkSpec - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._description = None
        self._nic = None
        self._node_name = None
        self._type = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if nic is not None:
            self.nic = nic
        self.node_name = node_name
        if type is not None:
            self.type = type

    @property
    def description(self):
        """Gets the description of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501


        :return: The description of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.


        :param description: The description of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def nic(self):
        """Gets the nic of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501


        :return: The nic of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._nic

    @nic.setter
    def nic(self, nic):
        """Sets the nic of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.


        :param nic: The nic of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :type: str
        """

        self._nic = nic

    @property
    def node_name(self):
        """Gets the node_name of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501


        :return: The node_name of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name):
        """Sets the node_name of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.


        :param node_name: The node_name of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and node_name is None:
            raise ValueError("Invalid value for `node_name`, must not be `None`")  # noqa: E501

        self._node_name = node_name

    @property
    def type(self):
        """Gets the type of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501


        :return: The type of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.


        :param type: The type of this NetworkHarvesterhciIoV1beta1NodeNetworkSpec.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkHarvesterhciIoV1beta1NodeNetworkSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkHarvesterhciIoV1beta1NodeNetworkSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkHarvesterhciIoV1beta1NodeNetworkSpec):
            return True

        return self.to_dict() != other.to_dict()
